### PR TITLE
add embedded shiny app for conjugate normal example

### PR DESCRIPTION
**Pull request by nanxstats**

### CODE REVIEW

**Comment by stephens999** [comment]
thanks @road2stat - I’m not sure it is behaving right. I tried
prior mu = 82
prior sigma = 2
data mu = 68
data sigma =  20

the posterior seems to be flatter than either the prior or the likelihood... which is odd?

**Comment by stephens999** [comment]
try also prior N(0,1) and likelihood N(0,1)

**Comment by stephens999** [comment]
oh, i may see the problem - you have an n, which means your "likelihood" is not really your likelihood (it is the likelihood to the power 1/n, or something)
Try setting = 1

**Comment by nanxstats** [comment]
- it seemed odd to me too... Thanks a lot for the hint, will update that soon.

**Comment by nanxstats** [comment]
@stephens999 An update is made in road2stat/conjugate-normal-umkv@1b85f36d8ef292ead7839eff658972e0c17f9fee
Hope it's fixed: http://nanx.me/fiveMinuteStats/analysis/shiny_normal_example.html

**Comment by stephens999** [comment]
Still not quite right. I think you want the user to give y (ie the observation) not the true parameter value (mu). When we do actual inference we don't know the truth, but we still calculate the prior and likelihood to get the posterior. 

Eg when the prior variance is very large check that the posterior and the likelihood are the same

**Comment by nanxstats** [comment]
Awesome, that has been fixed and details are improved in road2stat/conjugate-normal-umkv@07fcd7f2af67d2a2715bc5a2ad8738bc182e5750, check the updated app for details.

**Comment by stephens999** [comment]
@road2stat when i pulled it in i noticed it pulled in a whole bunch of files of the form
analysis/libs/bootstrap-3.3.5/css/..

what do those do?

**Comment by nanxstats** [comment]
@stephens999 they are the front-end libraries required by the generated htmls: https://github.com/rstudio/rmarkdown/tree/master/inst/rmd/h which are regularly updated by the rmarkdown package.

I guess ashlar will extract them from rmarkdown and put them in `libs`, but when the version number is different, there are no mechanisms to replace the old ones, resulting in some redundancy.

One workaround could be: we both update to the newest version of rmarkdown (knitr, etc.), remove all files inside `libs`, remove all previously generated htmls, and make all.

**Pull request merged**
